name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install eclipse-zenoh>=1.9.0 apache-iotdb>=2.0.0
        pip install pylint panel pandas
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
